### ISSUE TITLE
'charmap' codec can't encode character '\U0001f449' i

### ISSUE THREAD

**Issue by ivbeg** [AduchiMergen/tgarc#1]
При запуске команды
`tgarc  save --format json -o rosnano rosnanoinfo`

Среда: Windows 10, Python 3.8.10

Возвращает ошибку
```
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\tgarc.exe\__main__.py", line 7, in <module>
  File "C:\Python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Python38\lib\site-packages\main.py", line 128, in save
    new_offset_id = save_chat(app, chat, kwargs, offset_id)
  File "C:\Python38\lib\site-packages\main.py", line 181, in save_chat
    f.write(json.dumps(message, default=Object.default, ensure_ascii=False))
  File "C:\Python38\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f449' in position 1129: character maps to <undefined>
```

**Comment by AduchiMergen** [comment]
Fixed
