### ISSUE TITLE
TypeError: Client.__init__() got an unexpected keyword argument 'config_file'

### ISSUE THREAD

**Issue by l29ah** [AduchiMergen/tgarc#3]
```
$ ./main.py configure
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Api id: 611335
Api hash: d524b414d21f4d37f08684c1df41ac9c
Traceback (most recent call last):
  File "/home/test/tgarc/./main.py", line 223, in <module>
    cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/test/tgarc/./main.py", line 55, in configure
    with get_pyrogram_client() as app:
  File "/home/test/tgarc/./main.py", line 38, in get_pyrogram_client
    return Client("tgarc", workdir=str(get_work_dir()), config_file=str(get_config_path()))
TypeError: Client.__init__() got an unexpected keyword argument 'config_file'
```

**Comment by AduchiMergen** [comment]
fixed
